name: 'icapital-infra-user-tools-delete-on-issue'

on:
  issues:
    types: [opened]

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extrair TAG e Target da Descrição da Issue
        run: |
          TAG_NAME=$(echo "${{ github.event.issue.body }}" | grep -o -E 'TAG:\s+.+' | cut -d' ' -f2)
          TARGET_NAME=$(echo "${{ github.event.issue.body }}" | grep -o -E 'TARGET:\s+.+' | cut -d' ' -f2)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "TARGET_NAME=$TARGET_NAME" >> $GITHUB_ENV

      - name: Run Terraform Destroy
        run: |
          terraform init
          terraform destroy -auto-approve target="$TARGET_NAME" tags="Name=$TAG_NAME"
        working-directory: iCapital/AWS