name: 'icapital-infra-user-tools-delete-on-issue'

on:
  issues:
    types: [opened]

jobs:
  delete-resources:
    if: startsWith(github.event.issue.title, 'Delete')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extrair Target da descricao
        run: |
          TARGET_NAME=$(echo "${{ github.event.issue.body }}" | grep -o -E 'ARN:\s+.+' | cut -d' ' -f2)
          echo "TARGET_NAME=$TARGET_NAME" >> $GITHUB_ENV

      - name: Run Terraform Destroy
        working-directory: iCapital/AWS
        run: |
          terraform init
          terraform plan -input=false
          terraform destroy -auto-approve -target="$TARGET_NAME"