name: 'Delete resource'

on:
  issues:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Extract Resource ARN from Issue
        run: |
          export TAG_NAME=$(echo "${{ github.event.issue.title }}")
          echo "TAG $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $ARN_NAME

      - name: Run Terraform
        run: |
          terraform init
          terraform destroy -tags=Name=${{ env.TAG_NAME }}"

      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: >
            Recurso excluído com sucesso